services:
  maltrail-connector:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-tuttrue}/maltrail-connector:latest
    environment:
      - OPENCTI_URL=${OPENCTI_URL}
      - OPENCTI_TOKEN=${OPENCTI_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_ID}
      - CONNECTOR_NAME=${CONNECTOR_NAME}
      - CONNECTOR_SCOPE=${CONNECTOR_SCOPE}
      - CONNECTOR_LOG_LEVEL=${CONNECTOR_LOG_LEVEL}
      - CONNECTOR_TEMPLATE_API_BASE_URL=${GITHUB_API_BASE_URL}
      - CONNECTOR_TEMPLATE_API_KEY=${GITHUB_TOKEN}

    networks:
      - opencti_network
    restart: unless-stopped

networks:
  opencti_network:
    driver: bridge
